### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Kakalanp** [mengiefen/todo-list#5]
## Congrats @mengiefen! 🎉 

Your project not only look great ✨, it's also very organized and actually indestructible! 🛡️ 

I really have nothing to add 🥇, congratulations on solving the issues pointed out last time! 👍

**Comment by omar25ahmed** [comment]
Suggestions to change:
- after pressing the edit button it would be better if the input appears automatically
- after editing pressing Enter key to save would be a good option.

**Comment by mengiefen** [comment]
Dear partners, I have included the suggested improvements. Thank you! 🤞🏽
